export const ACTION_FETCH_FILTER_DATA = 'FETCH_FILTER_DATA';
export const ACTION_FETCH_FEATURED_PLAYLISTS = 'FETCH_FEATURED_PLAYLISTS';
export const ACTION_FETCH_AUTHORIZATION_CODE = 'FETCH_AUTHORIZATION_CODE';